### ISSUE TITLE
Issue with normalization

### ISSUE THREAD

**Issue by Ossscar** [linxihui/NNLM#19] opened 2020-05-20 22:42 UTC
Hi, 

The following part of the code in the nnmf function  does not produce the desired results and the normalization canno't be performed.

	if (W.norm > 0) {
		if (is.finite(W.norm)) {
			W.scale <- sapply(out$W, function(x) sum(x^W.norm)^(1./W.norm));
		} else {
			W.scale <- sapply(out$W, max);
			}
		out$W <- out$W %*% diag(1./W.scale);
		out$H <- diag(W.scale) %*% out$H
		}

**Comment by linxihui** [comment] 2021-03-06 21:20
Thanks for the report, the problem is fixed in #14

**Closed as completed** 2021-03-06 21:20 UTC
